spring.application.name=Noted

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/Noted
spring.datasource.username=postgres
spring.datasource.password=anirudh
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

server.servlet.session.cookie.same-site=strict